# -*- coding: utf-8 -*-

"""
/***************************************************************************
 OpenNHMQGisConnector
                                 A QGIS plugin
 Connects to AvaFrame
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-08-26
        copyright            : (C) 2021 by AvaFrame Team
        email                : felix@avaframe.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = "OpenNHM Team"
__date__ = "2026-02-23"
__copyright__ = "(C) 2026 by OpenNHM Team"

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = "$Format:%H$"

import sys
import os.path
import subprocess
import os
import inspect
from qgis.core import QgsProcessingProvider
from qgis.PyQt.QtGui import QIcon


from qgis.PyQt.QtWidgets import (
    QMessageBox,
)


# Check for avaframe, if not available, install...
# Note: this is still hacky, but we install into the same Python interpreter QGIS is running.
try:
    import avaframe
except ModuleNotFoundError:
    # Note: call pip via the current interpreter to ensure we install into the same
    # Python environment QGIS is running (works on Windows and Linux).
    cmd = [sys.executable, "-m", "pip", "install", "--user", "--upgrade", "avaframe"]
    proc = subprocess.run(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        check=False,
    )

    if proc.returncode != 0:
        QMessageBox.information(
            None,
            "AvaFrame installation failed",
            "Could not install AvaFrame via pip.\n\n"
            f"Python: {sys.executable}\n"
            f"Command: {' '.join(cmd)}\n\n"
            f"Output:\n{proc.stdout}",
        )

    try:
        import avaframe
    except ModuleNotFoundError:
        QMessageBox.information(
            None,
            "INFO",
            "AvaFrame is not available. If installation just ran, please restart QGIS.\n\n"
            f"Python: {sys.executable}\n"
            f"Command used: {' '.join(cmd)}",
        )

from .tools.avaframe.runFullOperational_algorithm import runFullOperationalAlgorithm
from .tools.avaframe.layerRename_algorithm import layerRenameAlgorithm
from .tools.avaframe.runCom1DFA_algorithm import runCom1DFAAlgorithm
from .tools.avaframe.runCom2AB_algorithm import runCom2ABAlgorithm
from .tools.avaframe.runCom9MoTVoellmy_algorithm import runCom9MoTVoellmyAlgorithm
from .tools.avaframe.runAna4ProbAna_algorithm import runAna4ProbAnaAlgorithm
from .tools.avaframe.runAna4ProbDirOnly_algorithm import runAna4ProbDirOnlyAlgorithm
from .tools.avaframe.runAna5DFAPathGeneration_algorithm import runAna5DFAPathGenerationAlgorithm
from .tools.avaframe.runCom5SnowSlide_algorithm import runCom5SnowSlideAlgorithm
from .tools.avaframe.runCom6RockAvalanche_algorithm import runCom6RockAvalancheAlgorithm
from .tools.avaframe.runCom7RegionalSplitting_algorithm import runCom7RegionalSplittingAlgorithm
from .tools.avaframe.runCom7RegionalComputation_algorithm import runCom7RegionalComputationAlgorithm
from .tools.avaframe.runCom6Scarp_algorithm import runCom6ScarpAlgorithm
from .tools.avaframe.runIn1RelInfo_algorithm import runIn1RelInfoAlgorithm
from .tools.avaframe.getDefaultModuleIni_algorithm import getDefaultModuleIniAlgorithm
from .tools.avaframe.loadPeakFiles_algorithm import loadPeakFilesAlgorithm
from .tools.admin.getVersion_algorithm import getVersionAlgorithm
from .tools.admin.update_algorithm import updateAlgorithm


class OpenNHMQGisConnectorProvider(QgsProcessingProvider):
    def __init__(self):
        """
        Default constructor.
        """
        QgsProcessingProvider.__init__(self)

    def flags(self):
        # return super().flags() | QgsProcessingAlgorithm.FlagNoThreading
        return super().flags()

    def unload(self):
        """
        Unloads the provider. Any tear-down steps required by the provider
        should be implemented here.
        """
        pass

    def loadAlgorithms(self):
        """
        Loads all algorithms belonging to this provider.
        """
        self.addAlgorithm(runFullOperationalAlgorithm())
        self.addAlgorithm(layerRenameAlgorithm())
        self.addAlgorithm(runCom1DFAAlgorithm())
        self.addAlgorithm(runCom2ABAlgorithm())
        self.addAlgorithm(runCom5SnowSlideAlgorithm())
        self.addAlgorithm(runCom6RockAvalancheAlgorithm())
        self.addAlgorithm(runCom6ScarpAlgorithm())
        # self.addAlgorithm(runCom8MoTPSAAlgorithm())
        self.addAlgorithm(runCom9MoTVoellmyAlgorithm())
        self.addAlgorithm(runCom7RegionalSplittingAlgorithm())
        self.addAlgorithm(runCom7RegionalComputationAlgorithm())
        self.addAlgorithm(runAna4ProbAnaAlgorithm())
        self.addAlgorithm(runAna4ProbDirOnlyAlgorithm())
        self.addAlgorithm(runAna5DFAPathGenerationAlgorithm())
        self.addAlgorithm(getVersionAlgorithm())
        self.addAlgorithm(updateAlgorithm())
        self.addAlgorithm(runIn1RelInfoAlgorithm())
        self.addAlgorithm(getDefaultModuleIniAlgorithm())
        self.addAlgorithm(loadPeakFilesAlgorithm())

    def id(self):
        """
        Returns the unique provider id, used for identifying the provider. This
        string should be a unique, short, character only string, eg "qgis" or
        "gdal". This string should not be localised.
        """
        return "OpenNHM"

    def name(self):
        """
        Returns the provider name, which is used to describe the provider
        within the GUI.
        """
        return self.tr("OpenNHM")

    def icon(self):
        """
        Should return a QIcon which is used for your provider inside
        the Processing toolbox.
        """
        cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]
        icon = QIcon(os.path.join(os.path.join(cmd_folder,  "icon.png")))
        return icon

    def longName(self):
        """
        Returns the longer version of the provider name, which can include
        extra details such as version numbers. E.g. "Lastools LIDAR tools
        (version 2.2.1)". This string should be localised. The default
        implementation returns the same string as name().
        """
        return self.name()
