# -*- coding: utf-8 -*-

"""
/***************************************************************************
 InstallDebrisFrame
                                 A QGIS plugin
 Connects to AvaFrame
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-09-24
        copyright            : (C) 2026 by AvaFrame Team
        email                : felix@avaframe.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = "AvaFrame Team"
__date__ = "2026"
__copyright__ = "(C) 2026 by AvaFrame Team"

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = "$Format:%H$"

import pathlib
from qgis.PyQt.QtCore import QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.core import (
    QgsProcessingAlgorithm,
    QgsProcessingParameterString,
)

from qgis.PyQt.QtWidgets import (
    QMessageBox,
)

# Qt5/Qt6 compatibility for the standard button enum.
try:
    _YES = QMessageBox.StandardButton.Yes
    _NO = QMessageBox.StandardButton.No
except AttributeError:
    _YES = QMessageBox.Yes
    _NO = QMessageBox.No


class installDebrisFrameAlgorithm(QgsProcessingAlgorithm):
    """
    Install DebrisFrame from PyPI, upgrading AvaFrame to a pre-release only after confirmation.
    """

    INPUT = "INPUT"

    def initAlgorithm(self, config=None):
        """
        Here we define the inputs and output of the algorithm,
        along with some other properties.
        """
        self.addParameter(
            QgsProcessingParameterString(
                self.INPUT,
                self.tr("Dummy input"),
                optional=True,
                defaultValue="Just leave this",
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        from ... import OpenNHMQGisConnector_provider as pv

        pythonExe = pv.getRealPythonExecutable()
        installedVersion = pv.getInstalledVersion("avaframe")
        needsConfirmation, commands = pv.buildDebrisFrameInstallPlan(pythonExe, installedVersion)
        manualCommand = " ".join(commands[0])

        if installedVersion is None:
            feedback.pushInfo("AvaFrame is not installed.")
        else:
            feedback.pushInfo("Installed AvaFrame version: " + installedVersion)

        # Only ask for confirmation when an existing older AvaFrame must be replaced.
        if needsConfirmation:
            message = (
                f"DebrisFrame requires AvaFrame >= {pv.minAvaFrameVersionForDebrisFrame}, which is a "
                "pre-release that pip does not install by default.\n\n"
                f"Proceeding will replace your installed AvaFrame (version {installedVersion}) "
                "with the latest pre-release.\n\n"
                f"If you prefer to do this manually, run:\n{manualCommand}"
            )
            answer = QMessageBox.question(
                None,
                "DebrisFrame requires a pre-release AvaFrame",
                message,
                _YES | _NO,
                _NO,
            )
            if answer != _YES:
                feedback.pushInfo("Installation aborted by user.")
                feedback.pushInfo("To install manually, run: " + manualCommand)
                return {}

        for command in commands:
            feedback.pushInfo("Running: " + " ".join(command))
            pv.runPip(command, feedback=feedback)

        feedback.pushInfo("---------------")
        feedback.pushInfo("DebrisFrame installation finished.")
        feedback.pushInfo("Restart QGIS for the DebrisFrame tools to appear.")
        feedback.pushInfo("---------------")

        return {}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return "InstallDebrisFrame"

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr("Install DebrisFrame")

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return "Admin"

    def tr(self, string):
        return QCoreApplication.translate("Processing", string)

    def shortHelpString(self) -> str:
        hstring = (
            "Installs the DebrisFrame python package from PyPI.\n"
            "DebrisFrame requires AvaFrame >= 2.2b1, which is a pre-release that pip does not install by "
            "default.\n"
            "If your installed AvaFrame is older, you are asked before it is upgraded to the latest "
            "pre-release.\n"
            "The DebrisFrame tools appear after restarting QGIS.\n"
            "The input is purely a dummy input, needed for this window to show up."
        )

        return self.tr(hstring)

    def helpUrl(self):
        return "https://docs.avaframe.org/en/latest/connector.html"

    def icon(self):
        icon_path = pathlib.Path(__file__).parent.parent.parent / "icon.png"
        return QIcon(str(icon_path))

    def createInstance(self):
        return installDebrisFrameAlgorithm()
